apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: totext
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jrichter/atta:30e299fdeaf629fd17d9bf3ef538d8ffdbc69286@sha256:f4c1d4ade76245f3bac9c6bdca9b480be9c88a1afb32404f16485a8856130a93 # use pre-built to bootstrap 
          name: app-inference
